# Generated by Django 3.1.2 on 2020-11-03 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preferences',
            name='pref_type',
            field=models.CharField(choices=[('summer_wear', 'Summer Wear'), ('winter_wear', 'Winter Wear'), ('foot_wear', 'Foot Wear'), ('ethnic_wear', 'Ethnic Wear'), ('western_wear', 'Western Wear'), ('accessories', 'Accessories'), ('fragrances', 'Fragrances')], default='top_wear', max_length=30, verbose_name='Type'),
        ),
    ]
