# Generated by Django 3.1.2 on 2020-11-03 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20201103_1553'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='datetime',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
