# Generated by Django 3.1.2 on 2020-11-19 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_item_datetime'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ['price']},
        ),
        migrations.AlterModelOptions(
            name='preferences',
            options={'ordering': ['title'], 'verbose_name': 'Preferences', 'verbose_name_plural': 'Preferences'},
        ),
        migrations.AddField(
            model_name='account',
            name='email_noification',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='account',
            name='sms_noification',
            field=models.BooleanField(default=False),
        ),
    ]
