# Generated by Django 3.1.2 on 2020-12-13 19:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_sale'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='sale_url',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
    ]
